CREATE TABLE "destination_list" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"institution" varchar(10),
	"destination" varchar(255),
	"district" varchar(255),
	"zone" varchar(255),
	"created_at" timestamp(6) with time zone DEFAULT now(),
	"updated_at" timestamp(6) with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "freight_list" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"institution" varchar(10),
	"date_effective" date,
	"dest_from" varchar(255),
	"dest_to" varchar(255),
	"km" numeric(10, 2),
	"rate_per_mt" numeric(10, 2),
	"rate_per_mt_above_4" numeric(10, 2),
	"rate_per_mt_upto_4" numeric(10, 2),
	"created_at" timestamp(6) with time zone DEFAULT now(),
	"updated_at" timestamp(6) with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "sales_register" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"institution" varchar(10),
	"date" date,
	"particulars" varchar(255),
	"buyer" varchar(255),
	"buyer_address" text,
	"consignee" varchar(255),
	"consignee_address" text,
	"voucher_type" varchar(100),
	"voucher_no" varchar(100),
	"voucher_ref_no" varchar(100),
	"sales_order_no" varchar(100),
	"sales_order_date" date,
	"dispatch_order_no" varchar(100),
	"dispatch_order_date" date,
	"zone" varchar(100),
	"district" varchar(100),
	"destination" varchar(255),
	"freight_rate" numeric(14, 2),
	"freight_amount" numeric(14, 2),
	"parent_1" varchar(255),
	"parent_2" varchar(255),
	"parent_3" varchar(255),
	"terms_of_payment" text,
	"terms_of_delivery" text,
	"dispatch_doc_no" varchar(100),
	"dispatch_through_party_name" varchar(255),
	"lr_no" varchar(100),
	"lr_date" date,
	"vehicle_no" varchar(50),
	"eway_bill_no" varchar(100),
	"gstin_uin" varchar(50),
	"sales_tax_no" varchar(50),
	"service_tax_no" varchar(50),
	"pan_no" varchar(50),
	"cst_no" varchar(50),
	"narration" text,
	"order_and_date" varchar(255),
	"other_references" varchar(255),
	"delivery_note_no_and_date" varchar(255),
	"place_of_receipt_by_shipper" varchar(255),
	"vessel_flight_no" varchar(100),
	"port_of_loading" varchar(255),
	"port_of_discharge" varchar(255),
	"country_to" varchar(100),
	"shipping_no" varchar(100),
	"shipping_date" date,
	"port_code" varchar(50),
	"item" varchar(255),
	"item_code" varchar(100),
	"quantity" numeric(14, 3),
	"uom" varchar(50),
	"alt_units" numeric(14, 3),
	"alt_uom" varchar(50),
	"rate" numeric(14, 2),
	"rate_per_bag" numeric(14, 2),
	"value" numeric(14, 2),
	"gross_total" numeric(14, 2),
	"inter_state_sales" numeric(14, 2),
	"inter_state_sales_5_percent" numeric(14, 2),
	"round_off" numeric(14, 2),
	"igst" numeric(14, 2),
	"cgst" numeric(14, 2),
	"sgst" numeric(14, 2),
	"inter_group_sale" numeric(14, 2),
	"sales_assam" numeric(14, 2),
	"sales_mizoram" numeric(14, 2),
	"sales_meghalaya" numeric(14, 2),
	"sales_nagaland" numeric(14, 2),
	"sales_arunachal" numeric(14, 2),
	"sales_tripura" numeric(14, 2),
	"created_at" timestamp(6) with time zone DEFAULT now(),
	"updated_at" timestamp(6) with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX "idx_destination_institution" ON "destination_list" USING btree ("institution");--> statement-breakpoint
CREATE INDEX "idx_destination_name" ON "destination_list" USING btree ("destination");--> statement-breakpoint
CREATE INDEX "idx_freight_institution_date" ON "freight_list" USING btree ("institution","date_effective");--> statement-breakpoint
CREATE INDEX "idx_sales_reg_inst_date" ON "sales_register" USING btree ("institution","date");--> statement-breakpoint
CREATE INDEX "idx_sales_reg_voucher" ON "sales_register" USING btree ("voucher_no");--> statement-breakpoint
CREATE INDEX "idx_sales_reg_buyer" ON "sales_register" USING btree ("buyer");